export default {
  items: [
    {
      id: 1,
      label: 'BXC',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img2.png',
    },
    {
      id: 2,
      label: 'G2H',
      description: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img1.png',
    },
    {
      id: 3,
      label: 'GHN',
      description: 'Вытяжное устройство с датчиком присутствия',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img3.png',
    },
    {
      id: 4,
      label: 'TDA',
      description: 'Вытяжное устройство с датчиком присутствия',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img4.png',
    },
    {
      id: 5,
      label: 'BXC5',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img2.png',
    },
    {
      id: 6,
      label: 'BXC6',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img1.png',
    },
    {
      id: 7,
      label: 'BXC7',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img3.png',
    },
    {
      id: 8,
      label: 'BXC8',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img4.png',
    },
    {
      id: 9,
      label: 'BXC9',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img2.png',
    },
    {
      id: 10,
      label: 'BXC10',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img1.png',
    },
    {
      id: 11,
      label: 'BXC11',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img3.png',
    },
    {
      id: 12,
      label: 'BXC12',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img4.png',
    },
    {
      id: 13,
      label: 'BXC13',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img1.png',
    },
    {
      id: 14,
      label: 'BXC14',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img2.png',
    },
    {
      id: 15,
      label: 'BXC15',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img3.png',
    },
    {
      id: 16,
      label: 'BXC16',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img4.png',
    },
    {
      id: 17,
      label: 'BXC17',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img2.png',
    },
    {
      id: 18,
      label: 'BXC18',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img1.png',
    },
    {
      id: 19,
      label: 'BXC19',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img3.png',
    },
    {
      id: 20,
      label: 'BXC20',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img4.png',
    },
    {
      id: 21,
      label: 'BXC21',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img2.png',
    },
    {
      id: 22,
      label: 'BXC22',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img1.png',
    },
    {
      id: 23,
      label: 'BXC23',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img3.png',
    },
    {
      id: 24,
      label: 'BXC24',
      description: 'Вытяжное устройство для механической системы вентиляции',
      priceRUB: '6 848 ₽ – 56 584 ₽ ',
      priceEURO: '77.60 € – 643.86 €',
      image: 'img4.png',
    },
  ],
}
